# frozen_string_literal: true

source 'https://rubygems.org'

gem 'grpc'
gem 'mecab_services_pb', path: '/mecab_services_pb'
gem 'sinatra'
gem 'rack-contrib'
gem 'rake'
gem 'mysql2'
gem 'activerecord', require: 'active_record'
