require './twilog_parser'

desc 'twilog_parser test'
task :run do
  IO.readlines('screen_names').each do |line|
    screen_name = line.chomp
    instance = TwilogParser::Parser.new
    tweets = instance.get(screen_name)
    tweets.dump_csv("dist/#{screen_name}.csv")
  end

end
