require './twilog_parser'

desc 'twilog_parser test'
task :run do
  IO.readlines('screen_names').each do |line|
    screen_name = line.chomp
    instance = TwilogParser::Parser.new
    tweets = instance.get(screen_name)
    tweets.dump_csv("dist/#{screen_name}.csv") if tweets.tweets.length > 100
  end
end

desc 'generate screen_names file'
task :generate_screen_name do
  File.open('screen_names', 'w') do |f|
    TwilogParser::Parser.new.get_user_list(limit: 30, offset: 30).each do |screen_name|
      f.puts screen_name
    end
  end
end
