a = []
a += ["popoyacomic", "hajimemashita_a", "JWWGJGGGWWW", "yomult", "razu_AD", "crm_sb", "ewC02AerS5DxdOi", "1013_jhnk", "leona_leon2009", "basasi21", "Makir0n", "terajima_katsu"]
a += ["ctutyn", "nasukunloml", "She_ca_ra_to_", "love_spl_ash", "__ame1025", "m_maru75", "pan_wo_kue", "usaxs_418", "219rst", "Avan_de_jinuor", "mcjj218", "Kforte120228", "kananephilim1", "Aosp115", "_muu_1223", "tomi_team", "blackbass_kc", "basasi21", "Makir0n", "terajima_katsu"]
a += ["numu_124", "Taj_Mahal_4469", "you57766077", "twotone_bot", "i9GeSADe4YjeXsK", "mizoknivesout", "Star_T_Rain", "hikki_free", "lovejump1117", "Doremi1204", "nanassi_00", "bnm96baMqAdRJ8h", "tuu_oyaji", "nuiipo", "tanaruru4", "Imw00Ib", "kazu_1915", "nizieroyasann", "pqf1717", "basasi21", "Makir0n", "terajima_katsu"]
a += ["6RB9qp5SJERuBt7", "VegaSF2_bot", "wafwaf612", "mirrativ_Takuto", "rinu_xo0212", "Irumina_07", "uwfLlx0wpOqReuD", "10hono_eli08", "djyuki710", "haunted_666", "m_0___0_n", "yatsugi_8", "hsou_u", "murakumo325", "ai10ya", "nakatake7869", "ilovesoccerlif1", "__rinarin5", "marutaroo_dr", "piyotta46", "basasi21", "Makir0n", "terajima_katsu"]
a += ["Manulca_cat", "aoichigo_0316u", "490drizzle", "aichanman0628", "kichimaru_31", "seiyui_k", "saa244", "maasa___", "nw_sgak_tatu07", "69music_life", "Rg_kb__r12a", "Low_Angle_AYTJ", "WqhZBScmW7emK6n", "ochiai5k", "masaren_bot", "basasi21", "Makir0n", "terajima_katsu"]
a +=["___ngomochi", "JJv8o", "green_eye_green", "yoshidasendai", "manaku78kurane", "FF14beginner_", "b1ack3uck", "kanpachi_PUBG", "sabayesmado", "elelell_poke", "uta_kata_kai20", "SeeDLacuS", "Tzu_0618", "magoroku2", "angelxo___", "freekuma11", "MaLu_coLu", "ura_sp0321", "TUvVxUZ30shnOhb", "basasi21", "Makir0n", "terajima_katsu"]
a += ["neet_nada", "kainumaasuka", "salon_amor", "imagawayaki_jf", "haru_chine", "0503_ku", "Haishin_P", "amiami_v", "to_T02", "basasi21", "Makir0n", "terajima_katsu"]
a += ["ReticentxPony", "veryfarfromhere", "maYumaY0_", "numacyu", "W_D_gs", "rin_chim_jm1013", "ks_azukijam", "majimurino_bot", "daodao0319", "takayan227", "mrety__", "QltZOkz1ZhYTdBO", "daishuke_bot", "MercyRO8", "Hawk_MatuKazu", "Mochiclub921", "rznprIxqFpzkZb2", "EttU0RJwaTYWtin", "SHSLOB_actor", "SIESTA8383", "basasi21", "Makir0n", "terajima_katsu"]
a += ["SIESTA8383", "yometo0me", "yui_uraaka_17", "omimi58338419", "otintinmeems", "tweekaddbot", "YaUmanohoneR", "Koujo_publicity", "straw_head_01", "Mt_caffe_latte", "hottomotto_com", "KnpakuDCJ", "kttk____0227", "wanwan_wanko__", "bananavinegar", "mu_kun1220", "FGO319", "ameameameame", "Sakurai_Lara2", "Aceloradrink", "basasi21", "Makir0n", "terajima_katsu"]
a += ["megu_shinonome", "yamy423117", "MOMOmop_6927", "risotto_100", "31pass19trr", "Merci0326_SLOU", "3m7a_niko2", "tu46296207", "114_gori", "siratuyu_sao", "panO3rll", "Cats_Ain", "blancolic_kaori", "777tade", "8skoic", "skiny_make", "rin_chim_jm1013", "ls_mf4", "Yuzu89191142", "basasi21", "Makir0n", "terajima_katsu"]
a += ["kintoun31", "natume__zz", "minakunnoheya", "_____5mg", "kosei11119", "tomonosuke3110", "kf_moe", "akanechanpanpi", "CardiacTrance", "hiyoko12piyo", "CallOfCasiDa", "MHT_KOUSHIKI", "BlueFlanker", "MeRodick_joooji", "librarian03", "onigasiraoparin", "UNOKI289", "koro_kororo_", "1210otakkii", "Rei90_game", "justjobhopping", "MHT_KOUSHIKI", "basasi21", "Makir0n", "terajima_katsu"]
a += ["MHT_KOUSHIKI", "_okapiiiiiokapi", "et_cetera07", "guri1024", "bobbynyan_fav", "meme31_21", "DarleyArabianbt", "yana_tuz", "k_kuroji", "ISaki1970", "_neginuki", "pervert_cheese", "Yuuuta_0204", "marshmallooo___", "AraREarAaraRA", "minato_Furrow", "MeMef0i_o71", "taiioouga", "FRONTIEEEEEEEER", "b_f_a17", "basasi21", "Makir0n", "terajima_katsu"]
a += ["ngc2497", "TOKIWA_IWAKI", "TomMukai", "nayun_kisei1", "taro_saitosan", "Pechimiya", "VIISense_fanbot", "_Hibiki_Anmothi", "kounenki____", "7vfYO8i9PjGgDdL", "AXLRIZE_1020", "MJlegend_miu", "Iyomante2", "Shulinpu_game", "Rei90_game", "Raphael6014", "kitten_bp", "soyo_shugyochu", "miko_kandora", "Tono_everystar", "udon_mitarasi", "basasi21", "Makir0n", "terajima_katsu"]
a += ["Tono_everystar", "udon_mitarasi", "ditchman5", "tagyo_udon", "INOUGAHOSII", "6ASUKAASUKA26", "love_nrs_", "INOUGAHOSII", "exia_ow", "Oka_cz", "Hossy_1425328", "10Love_twstuta", "Hyatt_Nazo", "tomy_1211_2nd", "Iamzofy", "INOUGAHOSII", "King_ofDTCM", "wdfield", "me_mkr", "riversatoi", "halscript", "Funa_moto", "basasi21", "Makir0n", "terajima_katsu"]
a += ["Funa_moto", "BIG_manju_Z", "Sw_Pino", "kofu_kobe", "Ae0TTcZKkKyTWBG", "doumocchi", "F__NEGIMA", "HarunaHanaoka", "srkm_2960", "findy_code", "xoxo19954", "Hqlunnn", "Yazuki_Michiko", "I3uta_", "kuro_zako", "Syuma_NMR", "dakuj3", "nosuke18", "tkykrn", "basasi21", "Makir0n", "terajima_katsu"]
a += ["dbsex7WYgNpKioM", "MHR000000", "m02297851", "suzuyutaro162cm", "nene720_love", "afilia_mio", "udon_mitarasi", "alima_series619", "kreis_schlange", "acide_guene", "whjeorifjeinjdh", "ysmk44512050", "wasuretenai_bot", "wanwan_love", "mkt__dayo", "Yazuki_Michiko", "petrocket1", "elSXy2vOdMxHrb8", "R34club", "huyuhi349122554", "samuson_pucci", "jj126_love_m827", "basasi21", "Makir0n", "terajima_katsu"]
a += ["akane_usi", "MOAKUN4649", "abackkana", "ruiruixrurarura", "9getSong", "anchovy0327", "douiku_bot", "jazzy10ran", "nurico_junkie", "komeokowa", "sikorun_bot", "udon_mitarasi", "pk_Viola", "elpda_TWO_3", "grvoo", "7_oq4", "XmMtBNRdTQhFE9x", "sleighbellscat", "Iso_569", "sora_ruirui", "fummykumi", "basasi21", "Makir0n", "terajima_katsu"]
a += ["fummykumi", "Chiffre007", "A_december7", "kaikun_nanako", "udon_mitarasi", "pikarinrin_07", "takuyasaaaan", "knkn_dujn4", "kgeRP6As6OXZK9n", "findy_code", "yu____chi__", "kinako_0901_jk", "Numakuro_4696", "aozora_is_HBS", "hitonanode", "mineruba11raika", "XqCr362", "catmaniax", "KiP5WypAgEgdPHD", "basasi21", "Makir0n", "terajima_katsu"]
a += ["Chiya_Craris", "AXLRIZE_1020", "chiro_waiwai", "caracoro00", "doumo_sawayaka", "hizuki_p", "pptworld007", "rahmensMac_bot", "hottomotto_com", "Filamegtg", "mobumyself___", "Milpixtwit", "1v4L43zy1zi51eI", "kajihara_meigen", "Tyoko79_", "Maru__kaki", "6sayaka2", "basasi21", "Makir0n", "terajima_katsu"]
a += ["PetitBonheur_01", "QOV8G7fGA4Kwqzb", "Kaitei_honten", "kyosei31", "GradationDays", "ssma_1205", "pinkie_koyubi", "EchosPhoto", "mohannsyuu43", "tetsubus_T", "so_nya121", "basasi21", "Makir0n", "terajima_katsu"]
a += ["green6beans", "warui_onigiri", "02_akira_05", "sayaai1", "2_pyramid", "hiroshimamania", "comsan_29q", "mikenyaagu", "basasi21", "Makir0n", "terajima_katsu"]
a += ["hirobusa_h", "hananeko_tw", "rikagothic128", "yu_sukeJr", "dono_m", "pink__nyannyan", "stedra_mhxx", "BerrySayuri", "k___fm", "effectgreen", "viiiivi226", "basasi21", "Makir0n", "terajima_katsu"]
a += ["CLUBREED1", "momo_chan_14", "yuka_ShellieMay", "dnbrsn_", "kani_misokan", "hbknb9", "sa_ruri_ra", "5hell11", "MED_echigo_shin", "yazhoujungpin", "f_M_AJ_", "FishermanWataru", "kinetsukinoa", "zeusnomama", "basasi21", "Makir0n", "terajima_katsu"]
a += ["7415Neko", "haratomo4945", "0710mikan1", "NYANKO2_1220", "kyatapirasu", "YocchiRider", "Tyorogon_0315", "CAkwUal2OTRHjQu", "LOVE_KF_KABU", "m_maaaaco", "basasi21", "Makir0n", "terajima_katsu"]
a += ["yu1005uu", "GoodGameOKINAWA", "hubuki729", "airutatvxq", "AziroGgg", "yoruyoru_death", "358Ririco", "likebloodymary", "basasi21", "Makir0n", "terajima_katsu"]
a += ["neon_0227", "yamachutitan", "chZukan", "mese_masquerade", "gokurin_mokuro", "Heidi_315", "akane_sugai_46", "Nozoshi", "LqsKu_sk", "basasi21", "Makir0n", "terajima_katsu"]
a += ["Heidi_315", "akane_sugai_46", "Nozoshi", "LqsKu_sk", "Guracor", "Pumopumo1", "kennkouotaku1", "tacica__bot", "NLaziLM", "bacaryau", "mars_1225", "asai_heiwa", "hamafuto", "kiribayasi", "yas_kawamura", "wv7IuaLaNxlxEkH", "301kakugen", "nyaaaaa_matsu", "Kansachin0520", "Mi4aachan", "kakituba16", "_99cafe_1", "hetasiennbot", "Mahoro_TWBot", "kndP_0701", "basasi21", "Makir0n", "terajima_katsu"]
a += ["yamatobisan05", "majyoalma_bot", "monokuro_kusiro", "Na_nmkw", "KruChis0817", "xx__not9", "hara2ki", "DaichApex", "pdos_h_a", "UL_kopipe", "_nanase247", "shiba249", "matunami_bucco", "yakisoba_EXX", "nedofu_atkun", "PTPN_Z", "kisaragi_celest", "ryoomu2", "e_erii_", "ayato276_LDH", "basasi21", "Makir0n", "terajima_katsu"]
a += ["nedofu_atkun", "PTPN_Z", "kisaragi_celest", "ryoomu2", "e_erii_", "ayato276_LDH", "KyoNago_Ba", "sUzbdFhOhG9yVz4", "mameii_9", "mu_pim390", "hikiyosed", "59Michael629", "3Arumeria", "KHJMT1", "TotoGeneral", "atumori_purin_", "yui_derideri", "aisyou_RT", "kurumi_kinow", "toraido777", "basasi21", "Makir0n", "terajima_katsu"]
a += ["AFK_LoseR", "ni_coa6", "kairi_ryokukei", "SNl8CZPEQXxJFlR", "2chjuken", "tttttbm11", "gD8ur7GHyfYBxdC", "yayoiroll", "SEIBU10000lover", "VeRyomu", "WonderSightTW", "kimera_pufu", "findy_code", "nhg_imouto", "youkanAM", "whbob931", "Free_Cportal", "O_F_WEL", "basasi21", "Makir0n", "terajima_katsu"]
a += ["zenitsu_kawaii_", "krump_nico", "sm_lunetia", "subwayjp", "crew_mafu__1222", "tennis_erika_", "yume_0430", "korumaro___423", "kirenaif", "taa_fin30", "music_sakurai", "majyoalma_bot", "KOJ_T_METAL", "cayucca", "sasaki666", "mao0322mao", "TigerThanBlack", "Maya_E_ster9", "skc_anniversary", "nicemiddletwoos", "xxxxRaiaxxxx", "basasi21", "Makir0n", "terajima_katsu"]
a += ["mao0322mao", "TigerThanBlack", "Maya_E_ster9", "skc_anniversary", "nicemiddletwoos", "xxxxRaiaxxxx", "nanamisindou", "fokkun1", "Sin2003913", "FIzif03kzPfLzGl", "m_outsiderdesu", "sachi_kudou", "tofu_2co", "iiiyuriii_2", "yuki6yukimi", "takotarongeki", "keiba83919486", "zakisan_yade", "Momiji_514", "basasi21", "Makir0n", "terajima_katsu"]
a += ["karurazeta", "kokokun_123", "unubore_party", "ayunotaiyaki", "kousetsu_neni", "Noche_aruaru", "nakanaka6270", "rei91322", "zero_of_zin", "yuzuki1019", "aooooookun", "shizuho_h", "___Niiki09", "hottomotto_com", "Tag_1004_jh", "moko6x6", "Donbuku_Chaya", "anime_sougo_com", "ShijinBot", "amyels001", "TvE_SHELTER", "noyu_cos", "basasi21", "Makir0n", "terajima_katsu"]
a += ["jiyon_onma", "anzutio11", "_tmhroO", "sexxxsaran", "perocan__i_i", "03kustom", "yutan_phys_gt", "dadamone1002", "mozu_kszs", "5668juCF", "moritsukimiya", "HOTARUMARU_10", "jire_yama", "kiremenosake", "tetrax4xtiger", "Milk_vrchat", "TAKU_nichan", "basasi21", "Makir0n", "terajima_katsu"]
a += ["ymdz888", "sns45454", "kkzy_pkgbot", "kuraara________", "sp__Lee", "Hasa0418", "ka_ta_kata", "IHZ7B02zZgUb8Tx", "pobeyama", "kou_saikontan", "RAKZAX_SPECTOL", "misto_TRPG", "ju_87g1lwhurvs4", "Riley_c6", "Ss_r103", "okmwtiset2", "worrior_mk3", "summersanta1000", "Lusora_", "basasi21", "Makir0n", "terajima_katsu"]
a += ["VkAm9A69b5uUxO2", "hogeohoge", "koukou_0830", "sipisipi_an", "printfsoku", "teto37O", "adultdaisuk", "xo__kyohei", "maya_noho", "a__ih99", "kata_shortening", "tokeruphase", "chelsy_yui", "cBE4HHY30b3fSL0", "Frank_Orte", "ASKredd_3", "tk__s5", "cleanFYTT", "maroyamanago", "Tomo88271492", "basasi21", "Makir0n", "terajima_katsu"]

a = a.uniq
puts a
File.open("screen_names", 'w') do |f|
  a.each do |e|
    f.puts e
  end
end
# [].slice.call(document.getElementsByClassName('css-4rbku5 css-18t94o4 css-1dbjc4n r-sdzlij r-1loqt21 r-1adg3ll r-ahm1il r-1ny4l3l r-1udh08x r-o7ynqc r-6416eg r-13qz1uu')).map(x => x.href.split('/')[3])
